# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
development:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: corgi_engine
  pool: 5
  username: corgi_engine
  password: corgi_engine
  socket: /tmp/mysql.sock

test:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: corgi_engine_test
  pool: 5
  username: corgi_engine
  password: corgi_engine
  socket: /tmp/mysql.sock

production:
  host: DB_HOST
  adapter: mysql2
  encoding: utf8
  database: DB_NAME
  pool: 5
  username: DB_USER
  password: DB_PWD
  socket: /var/lib/mysql/mysql.sock
  reconnect: true
