# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
development:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: corgi_portal
  pool: 5
  username: corgi_portal
  password: corgi_portal
  socket: /tmp/mysql.sock

test:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: corgi_portal_test
  pool: 5
  username: corgi_portal
  password: corgi_portal
  socket: /tmp/mysql.sock

# corgi:
#   adapter: mysql2
#   encoding: utf8
#   reconnect: false
#   database: corgi
#   pool: 5
#   username: corgi
#   password: corgi
#   socket: /tmp/mysql.sock